# Author: Michael Valdron
FROM --platform=$BUILDPLATFORM docker.io/library/alpine:3.23.3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659

# Package Envs
# renovate: datasource=repology depName=alpine_3_23/bash versioning=loose
ENV BASH_VERSION="5.3.3-r1"
# renovate: datasource=repology depName=alpine_3_23/curl versioning=loose
ENV CURL_VERSION="8.17.0-r1"
# renovate: datasource=repology depName=alpine_3_23/zip versioning=loose
ENV ZIP_VERSION="3.0-r13"
# renovate: datasource=repology depName=alpine_3_23/unzip versioning=loose
ENV UNZIP_VERSION="6.0-r16"
# renovate: datasource=repology depName=alpine_3_23/gcompat versioning=loose
ENV GCOMPAT_VERSION="1.1.0-r4"
# renovate: datasource=repology depName=alpine_3_23/openjdk25 versioning=loose
ENV OPENJDK_VERSION="25.0.2_p10-r1"
# renovate: datasource=repology depName=alpine_3_23/clojure versioning=loose
ENV CLOJURE_VERSION="1.12.3-r0"
# renovate: datasource=repology depName=alpine_3_23/rlwrap versioning=loose
ENV RLWRAP_VERSION="0.47.1-r0"
# renovate: datasource=repology depName=alpine_3_23/leiningen versioning=loose
ENV LEININGEN_VERSION="2.12.0-r0"
# renovate: datasource=repology depName=alpine_3_23/nodejs versioning=loose
ENV NODE_VERSION="24.13.0-r1"
# renovate: datasource=repology depName=alpine_3_23/npm versioning=loose
ENV NPM_VERSION="11.6.3-r0"
# renovate: datasource=repology depName=alpine_3_23/python3 versioning=loose
ENV PYTHON_VERSION="3.12.12-r0"
# renovate: datasource=repology depName=alpine_3_23/py3-pip versioning=loose
ENV PIP_VERSION="25.1.1-r1"
# renovate: datasource=repology depName=alpine_3_23/uv versioning=loose
ENV UV_VERSION="0.9.26-r0"
# renovate: datasource=repology depName=alpine_3_23/go versioning=loose
ENV GO_VERSION="1.25.7-r0"
# renovate: datasource=npm depName=corepack versioning=loose
ENV COREPACK_VERSION="0.34.6"
# renovate: datasource=npm depName=nvm versioning=loose
ENV NVM_VERSION="0.40.4"
# renovate: datasource=npm depName=yarn versioning=loose
ENV YARN_VERSION="4.12.0"

# Install System Packages
RUN apk update && apk add bash=${BASH_VERSION} curl=${CURL_VERSION} zip=${ZIP_VERSION} unzip=${UNZIP_VERSION} gcompat=${GCOMPAT_VERSION} \
  openjdk25=${OPENJDK_VERSION} \
  clojure=${CLOJURE_VERSION} rlwrap=${RLWRAP_VERSION} leiningen=${LEININGEN_VERSION} leiningen-bash-completion=${LEININGEN_VERSION} \
  nodejs=${NODE_VERSION} npm=${NPM_VERSION} \
  python3=${PYTHON_VERSION} py3-pip=${PIP_VERSION} uv=${UV_VERSION} uv-bash-completion=${UV_VERSION} \
  go=${GO_VERSION}

# Install corepack
RUN npm install -g corepack@${COREPACK_VERSION}

# Create user
RUN addgroup --gid 1000 dev \
  && adduser --home /home/dev --shell /bin/bash --uid 1000 --ingroup dev --disabled-password dev

# Add working directory
RUN mkdir -p /project && chown -R dev:dev /project

# Set user
USER 1000

# Download and install nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh | bash
ENV NVM_DIR=/home/dev/.nvm
RUN echo 'source $NVM_DIR/nvm.sh' >> ~/.bashrc

# Install yarn
RUN corepack enable && corepack prepare yarn@${YARN_VERSION} --activate

# Install sdkman
ENV SDKMAN_DIR=/home/dev/.sdkman
RUN curl -s "https://get.sdkman.io?ci=true" | bash

# Set user install bin directory to path
ENV PATH="~/.local/bin:$PATH"

# Set working directory
WORKDIR /project

# Labels
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.build-date=${BUILD_DATE}
LABEL org.label-schema.name="michaelvaldron/dev"
LABEL org.label-schema.description="Base developer container image"

# Reload user environments
ENTRYPOINT ["bash", "-c", "source $SDKMAN_DIR/bin/sdkman-init.sh && source $NVM_DIR/nvm.sh && $@", "--"]

# "CMD" runs an initial command on container startup
CMD ["/bin/bash"]
