# Author: Michael Valdron
FROM --platform=$BUILDPLATFORM docker.io/library/alpine:3.23.3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659

# Build Args
ARG NVM_VERSION=0.40.4
ARG YARN_VERSION=4.12.0
ARG SDKMAN_VERSION=5.7.0

# Install System Packages
RUN apk update && apk add bash=5.3.3-r1 curl=8.17.0-r1 zip=3.0-r13 unzip=6.0-r16 gcompat=1.1.0-r4 \
  openjdk25=25.0.2_p10-r1 clojure=1.12.3-r0 rlwrap=0.47.1-r0 \
  nodejs=24.13.0-r1 npm=11.6.3-r0 \
  python3=3.12.12-r0 py3-pip=25.1.1-r1 uv=0.9.26-r0 uv-bash-completion=0.9.26-r0 \
  go=1.25.7-r0

# Install corepack
RUN npm install -g corepack

# Create user
RUN addgroup --gid 1000 dev \
  && adduser --home /home/dev --shell /bin/bash --uid 1000 --ingroup dev --disabled-password dev

# Add working directory
RUN mkdir -p /project && chown -R dev:dev /project

# Set user
USER 1000

# Download and install nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh | bash
ENV NVM_DIR=/home/dev/.nvm
RUN echo 'source $NVM_DIR/nvm.sh' >> ~/.bashrc

# Install yarn
RUN corepack enable && corepack prepare yarn@${YARN_VERSION} --activate

# Install sdkman
ENV SDKMAN_DIR=/home/dev/.sdkman
ENV SDKMAN_VERSION=${SDKMAN_VERSION}
RUN curl -s "https://get.sdkman.io?ci=true" | bash

# Set user install bin directory to path
ENV PATH="~/.local/bin:$PATH"

# Set working directory
WORKDIR /project

# Labels
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.build-date=${BUILD_DATE}
LABEL org.label-schema.name="michaelvaldron/dev"
LABEL org.label-schema.description="Base developer container image"

# Reload user environments
ENTRYPOINT ["bash", "-c", "source $SDKMAN_DIR/bin/sdkman-init.sh && source $NVM_DIR/nvm.sh && $@", "--"]

# "CMD" runs an initial command on container startup
CMD ["/bin/bash"]
