# Author: Michael Valdron
FROM docker.io/library/debian:13.3-slim@sha256:1d3c811171a08a5adaa4a163fbafd96b61b87aa871bbc7aa15431ac275d3d430

# Package Envs
# renovate: datasource=repology depName=debian_13/curl versioning=loose
ENV CURL_VERSION="8.14.1-2+deb13u2"
# renovate: datasource=repology depName=debian_13/zip versioning=loose
ENV ZIP_VERSION="3.0-15"
# renovate: datasource=repology depName=debian_13/unzip versioning=loose
ENV UNZIP_VERSION="6.0-29"
# renovate: datasource=repology depName=debian_13/openjdk-25-jdk versioning=loose
ENV OPENJDK_VERSION="25.0.2+10-1~deb13u2"
# renovate: datasource=repology depName=debian_13/clojure versioning=loose
ENV CLOJURE_VERSION="1.12.0-1"
# renovate: datasource=repology depName=debian_13/leiningen versioning=loose
ENV LEININGEN_VERSION="2.10.0-5"
# renovate: datasource=repology depName=debian_13/nodejs versioning=loose
ENV NODE_VERSION="20.19.2+dfsg-1"
# renovate: datasource=repology depName=debian_13/node-corepack versioning=loose
ENV COREPACK_VERSION="0.24.0-5"
# renovate: datasource=repology depName=debian_13/yarnpkg versioning=loose
ENV YARN_VERSION="4.1.0+dfsg-1"
# renovate: datasource=repology depName=debian_13/python3 versioning=loose
ENV PYTHON_VERSION="3.13.5-1"
# renovate: datasource=repology depName=debian_13/python3-pip versioning=loose
ENV PIP_VERSION="25.1.1+dfsg-1"
# renovate: datasource=repology depName=debian_13/golang-1.24 versioning=loose
ENV GO_VERSION="1.24.4-1"
# renovate: datasource=pypi depName=uv versioning=loose
ENV UV_VERSION="0.9.26"
# renovate: datasource=github-releases depName=nvm-sh/nvm versioning=loose
ENV NVM_VERSION="0.40.4"

# Install System Packages
RUN apt update -y && apt install -y curl=${CURL_VERSION} zip=${ZIP_VERSION} unzip=${UNZIP_VERSION} \
  openjdk-25-jre-headless=${OPENJDK_VERSION} openjdk-25-jdk-headless=${OPENJDK_VERSION} \
  clojure=${CLOJURE_VERSION} leiningen=${LEININGEN_VERSION} \
  nodejs=${NODE_VERSION} node-corepack=${COREPACK_VERSION} yarnpkg=${YARN_VERSION} \
  python3=${PYTHON_VERSION} python3-pip=${PIP_VERSION} \
  golang=2:1.24~2 golang-1.24=${GO_VERSION} golang-1.24-go=${GO_VERSION}

# Create yarn symlink
RUN ln -s /usr/bin/yarnpkg /usr/local/bin/yarn

# Create user
RUN addgroup --gid 1000 dev \
  && adduser --home /home/dev --shell /bin/bash --uid 1000 --ingroup dev --disabled-password dev

# Add working directory
RUN mkdir -p /project && chown -R dev:dev /project

# Set user
USER 1000

# Set user install bin directory to path
ENV PATH="~/.local/bin:$PATH"

# Install uv
RUN curl -LsSf https://astral.sh/uv/${UV_VERSION}/install.sh | sh

# Download and install nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh | bash
ENV NVM_DIR=/home/dev/.nvm
RUN echo 'source $NVM_DIR/nvm.sh' >> ~/.bashrc

# Install sdkman
ENV SDKMAN_DIR=/home/dev/.sdkman
RUN curl -s "https://get.sdkman.io?ci=true" | bash

# Set clojure alias
RUN echo "alias clj='clojure'" >> ~/.bashrc

# Set working directory
WORKDIR /project

# Labels
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.build-date=${BUILD_DATE}
LABEL org.label-schema.name="michaelvaldron/dev"
LABEL org.label-schema.description="Base developer container image"

# Reload user environments
ENTRYPOINT ["bash", "-c", "source $SDKMAN_DIR/bin/sdkman-init.sh && source $NVM_DIR/nvm.sh && $@", "--"]

# "CMD" runs an initial command on container startup
CMD ["/bin/bash"]
